name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - sonarQ
      - 2-corregir-los-errores-de-mantenibilidad
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set working directory
        run: cd Dashboard_Ambiental

      - name: Install dependencies
        working-directory: Dashboard_Ambiental
        run: npm install

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: Dashboard_Ambiental
          args: >
            -Dsonar.projectKey=Dashboard_Ambiental
            -Dsonar.organization=dweskz
            -Dsonar.sources=src
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
